### ISSUE TITLE
When using nvdifast on multiple GPUs, lock file exists in build directory appears

### ISSUE THREAD

**Issue by Fjzd** [NVlabs/nvdiffrast#145] opened 2023-11-25 02:32 UTC
When using nvdifast on multiple GPUs, lock file exists in build directory appears

**Comment by s-laine** [comment] 2023-11-26 10:53
Duplicate of #67

**Closed by s-laine** 2023-11-26 10:53 UTC

**Comment by jpainam** [comment] 2024-02-26 19:40
what file should I delete? `./cache/torch_extensions/nvdiffrast_plugin/lock'`, only the `lock` file or all the `nvdiffrast_plugin` extension?
